spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
  output:
    ansi:
      enabled: ALWAYS

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET}