spring:
  application:
    name: blackjackapp

  data:
    mongodb:
      database: ${MONGODB_DATABASE}
      uri: ${MONGODB_URI}

  r2dbc:
    url: ${MYSQL_R2DBC_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}

## EJECUCIÓN EN LOCAL:
#
## swagger
## http://localhost:8080/v3/api-docs
## http://localhost:8080/swagger-ui/index.html#/
#