spring:
  application:
    name: blackjackapp

  data:
    mongodb:
      database: blackjack_app_games
      uri: mongodb://localhost:27017

  r2dbc:
    url: r2dbc:mysql://localhost:3306/blackjack_app_players
    username: root
    password: 1707

  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8080

jwt:
  secret: my-super-secret-key-123456